server:
  port: 8090
  servlet:
    context-path: /example
mybatis:
  configuration:
    cache-enabled: true # 激活二级缓存
  type-aliases-package: com.gm.entry # 定义所以操作类的别名
  mapper-locations:
    - classpath:com.gm.mapper/*.xml # mapper.xml文件的位置


spring:
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource #使用的数据源
    driver-class-name: com.mysql.jdbc.Driver # 数据库连接驱动
    url: jdbc:mysql://localhost:3306/test?useSSL=false # 数据库连接url
    username: root #用户名
    password: gm0408 # 密码
    dbcp2: # 连接池
      min-idle: 5 # 最小活跃数
      initial-size: 5 # 初始化连接数
      max-idle: 10 # 最大活跃数
      max-total: 15 # 连接池最大容量
      max-wait-millis: 200 # 等待连接的最大获取时间
  # 配置spring boot的热加载
  devtools:
    restart:
      enabled: true

pagehelper:     # 分页插件
  # dialect: MySql # 设置数据库方言
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql


logging:
  #level: debug
#file: ./logs/application.log
